lzc-sdk-version: "0.1"
name: Ech0
package: cloud.lazycat.app.ech0
version: 3.4.4
description: 开源、自托管、专注思想流动的轻量级发布平台
homepage: https://github.com/lin-snow/Ech0
author: lin-snow
application:
  subdomain: lin-snow
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://ech0:1314/
services:
  ech0:
    image: docker.hlmirror.com/sn0wl1n/ech0:v3.4.4
    binds:
      - /lzcapp/var/data:/app/data
