application:
  subdomain: ech0-ng
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://ech0:6277/
services:
  ech0:
    #sn0wl1n/ech0:v2.9.6
    # upstream: docker.io/sn0wl1n/ech0:v5.7.0
    image: registry.lazycat.cloud/czyt/sn0wl1n/ech0:e6c7991a56891d25
    binds:
      - /lzcapp/var/data:/app/data
    environment:
      - JWT_SECRET={{stable_secret "ech0#jwt" | substr 0 32}}
